  version: '3.8'

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
        target: build
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/streaming
        - SPRING_PROFILES_ACTIVE=dev
#        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
#        - AWS_SECRET_KEY=${AWS_SECRET_KEY}
#        - AWS_REGION=${AWS_REGION}
#        - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      volumes:
        - ./src:/app/src
        - ./target:/app/target
        - maven-repo:/root/.m2
      depends_on:
        - mongodb
      networks:
        - streaming-network
      restart: unless-stopped

    mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      environment:
        - MONGO_INITDB_DATABASE=streaming
      networks:
        - streaming-network
      restart: unless-stopped

    prometheus:
      image: prom/prometheus:latest
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      networks:
        - streaming-network
      restart: unless-stopped


    grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
        - grafana_data:/var/lib/grafana
      depends_on:
        - prometheus
      networks:
        - streaming-network
      restart: unless-stopped

  volumes:
    mongodb_data:
    grafana_data:
    maven-repo:

  networks:
    streaming-network:
      driver: bridge
