  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: movie-streaming
    labels:
      app: movie-streaming
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: movie-streaming
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          app: movie-streaming
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: "/actuator/prometheus"
          prometheus.io/port: "8080"
      spec:
        containers:
          - name: movie-streaming
            image: __IMAGE__
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "500m"
                memory: "512Mi"
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "prod"
              - name: SPRING_DATA_MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: mongodb-credentials
                    key: uri
              - name: AWS_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: access-key
              - name: AWS_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: secret-key
              - name: AWS_REGION
                valueFrom:
                  configMapKeyRef:
                    name: aws-config
                    key: region
              - name: AWS_S3_BUCKET
                valueFrom:
                  configMapKeyRef:
                    name: aws-config
                    key: bucket
            livenessProbe:
              httpGet:
                path: /actuator/health/liveness
                port: 8080
              initialDelaySeconds: 60
              periodSeconds: 15
            readinessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 10
