apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: movie-streaming
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false