apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-streaming
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  tls:
    - hosts:
        - api.movie-streaming.com
      secretName: movie-streaming-tls
  rules:
    - host: api.movie-streaming.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movie-streaming
                port:
                  number: 8085
