apiVersion: v1
kind: Service
metadata:
  name: movie-streaming
  labels:
    app: movie-streaming
spec:
  selector:
    app: movie-streaming
  ports:
    - port: 8085
      targetPort: 8085
      name: http
  type: ClusterIP
